openapi: 3.0.0
info:
  title: Bank Of ComputerCraft API
  description: API for Bank Of ComputerCraft
  version: 1.1.0
servers:
  - url: https://ccbank.tkbstudios.com/api/v1
    description: Production server
paths:
  /version:
    get:
      summary: Get API version
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: '1.1.0'
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                pin:
                  type: string
              required:
                - username
                - pin
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login successful
                  session_token:
                    type: string
                    example: a98d7f67-0945-4efc-bb36-831e9e1837f9
        '401':
          description: Invalid username or PIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid username or PIN
  /change-pin:
    post:
      summary: Change user PIN
      security:
        - SessionToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_pin:
                  type: string
              required:
                - new_pin
      responses:
        '200':
          description: PIN changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: PIN changed successfully
  /balance:
    get:
      summary: Get user balance
      security:
        - SessionToken: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    example: 100.0
  /transactions/new:
    post:
      summary: Create new transaction
      security:
        - SessionToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                amount:
                  type: number
              required:
                - username
                - amount
      responses:
        '202':
          description: Transaction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Transaction successful
                  transaction_id:
                    type: integer
                    example: 12345
  /transactions/list:
    get:
      summary: List user transactions
      security:
        - SessionToken: []
      parameters:
        - name: per_page
          in: query
          description: Number of transactions per page
          required: false
          schema:
            type: integer
            default: 15
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    from_user:
                      type: string
                    to_user:
                      type: string
                    amount:
                      type: number
                    id:
                      type: integer
  /transactions/info/{id}:
    get:
      summary: Get information about a specific transaction
      security:
        - SessionToken: []
      parameters:
        - name: id
          in: path
          description: ID of the transaction to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  from_user:
                    type: string
                  to_user:
                    type: string
                  amount:
                    type: number
                  id:
                    type: integer
  /latest-client:
    get:
      summary: Redirect to the latest version of the ComputerCraft client script
      responses:
        '302':
          description: Redirect
          content:
            application/json:
              schema:
                type: string
                example: Redirecting to the latest client script...
  /latest-pocket-client:
    get:
      summary: Redirect to the latest version of the ComputerCraft pocket client script
      responses:
        '302':
          description: Redirect
          content:
            application/json:
              schema:
                type: string
                example: Redirecting to the latest pocket client script...
  /v1/subaccounts/create:
    post:
      summary: Create new subaccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Subaccount created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Subaccount created successfully
                  subaccount_id:
                    type: integer
  /v1/subaccounts/list:
    get:
      summary: List user subaccounts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    balance:
                      type: number
  /v1/subaccounts/get/{subaccount_id}:
    get:
      summary: Get information about a specific subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  balance:
                    type: number
  /v1/subaccounts/delete/{subaccount_id}:
    delete:
      summary: Delete a subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subaccount deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Subaccount deleted successfully
  /v1/subaccounts/update/{subaccount_id}:
    post:
      summary: Update a subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Subaccount updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Subaccount updated successfully
  /v1/subaccounts/transactions/create:
    post:
      summary: Create new transaction for a subaccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subaccount_id:
                  type: integer
                amount:
                  type: number
                note:
                  type: string
              required:
                - subaccount_id
                - amount
      responses:
        '200':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Transaction created successfully
                  details:
                    type: object
                    properties:
                      subaccount_id:
                        type: integer
                      id:
                        type: integer
                      amount:
                        type: integer
                      note:
                        type: string
                      date:
                        type: string
                        format: date-time
                    example:
                      subaccount_id: 123
                      id: 456
                      amount: 100
                      note: "Transaction note"
                      date: "2024-04-04T12:00:00Z"
  /v1/subaccounts/transactions/list/{subaccount_id}:
    get:
      summary: List transactions for a subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    amount:
                      type: number
                    id:
                      type: integer
                    note:
                      type: string
                    date:
                      type: string
  /v1/subaccounts/transactions/count/{subaccount_id}:
    get:
      summary: Get count of transactions for a subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
  /v1/subaccounts/transactions/info/{subaccount_id}/{transaction_id}:
    get:
      summary: Get information about a specific transaction for a subaccount
      parameters:
        - name: subaccount_id
          in: path
          description: ID of the subaccount
          required: true
          schema:
            type: string
        - name: transaction_id
          in: path
          description: ID of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: number
                  id:
                    type: integer
                  note:
                    type: string
                  date:
                    type: string
components:
  securitySchemes:
    SessionToken:
      type: apiKey
      in: header
      name: Session-Token
security:
  - SessionToken: []
